export * from "./FiltersSVG";
export * from "./WarningSVG";
export * from "./LogoSVG";
export * from "./GoogleSVG";
export * from "./RightSVG";
export * from "./LoaderOvalSVG";
export * from "./CrossSVG";
export * from "./LeftArrowSVG";
export * from "./TopRightArrowSVG";
export * from "./InfoSVG";
export * from "./FaceSVG";
export * from "./OutBoxSVG";
export * from "./EyeSVG";
export * from "./EyeOffSVG";
export * from './NoImgSVG'
export * from './LocationSVG'
export * from './CopySVG'
export * from './EyeOffSVG'
export * from './PencilSVG'
export * from './RightArrowSVG'
export * from './TopArrowSVG'
export * from './User2SVG'
export * from './UserSVG'