/* eslint-disable @next/next/no-page-custom-font */
import "@/shared/styles/globals.css";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/dates/styles.layer.css";
import "@mantine/tiptap/styles.css";
import type { Metadata } from "next";
import { Box, ColorSchemeScript, Flex, MantineProvider } from "@mantine/core";
import { theme } from "@/shared/config/mantine.config";
import { Header } from "@/widgets/Header";
import { Cursor } from "../shared/ui/Cursor";
import { Footer } from "@/widgets/Footer";
import { HideWhen } from "@/shared/ui";
import { MantineHiddThemeSwitch } from "./(main_page)/MantineHiddThemeSwitch";


export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headAndFootHiddened = [
    "/auth/",
    "/create_fundraiser/names",
    "/create_fundraiser/amount",
    "/donation_method",
  ];

  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="light" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="light">
          <Box maw={"100%"} w={"100%"} style={{ overflow: "hidden" }}>
            <Flex mih={"100vmin"} direction={"column"}>
              <HideWhen routes={headAndFootHiddened}>
                <Header />
              </HideWhen>
              <Cursor />
              <Box flex={"1 1 auto"}>{children}</Box>
              <HideWhen routes={headAndFootHiddened}>
                <Footer />
              </HideWhen>
            </Flex>
          </Box>
          <MantineHiddThemeSwitch />
        </MantineProvider>
      </body>
    </html>
  );
}
