import type { Metadata } from "next";
import "./globals.css";
import { ColorSchemeScript, MantineProvider, Title } from "@mantine/core";
import { theme } from "@/shared/config/mantine.config";
import "@mantine/core/styles.css";
import { Header } from "@/widgets/Header";
import AuthProvider from "@/shared/providers/AuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="light" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="light">
          <AuthProvider session={session}>
            <Header />
            {children}
          </AuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
